export const FETCH_ALL_PHARMACIES = "FETCH_ALL_PHARMACIES";
export const FETCH_ALL_PHARMACIES_SUCCESS = "FETCH_ALL_PHARMACIES_SUCCESS";
export const FETCH_ALL_PHARMACIES_FAILED = "FETCH_ALL_PHARMACIES_FAILED";
export const FETCH_ALL_MEDS = "FETCH_ALL_MEDS";
export const FETCH_ALL_MEDS_SUCCESS = "FETCH_ALL_MEDS_SUCCESS";
export const FETCH_ALL_MEDS_FAILED = "FETCH_ALL_MEDS_FAILED";
export const SET_SELECTED_PHARMACY = "SET_SELECTED_PHARMACY";
export const SET_MAP_CENTER = "SET_MAP_CENTER";


